server:
  port: 9000
spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/DGDP?oracle.net.disableOob=true
    username: dgdp
    password: dgdp
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      poolName: HikariPoolDgdp
      minimumIdle: 5
      maximumPoolSize: 20
      idleTimeout: 600000
      maxLifetime: 1800000
      connectionTimeout: 30000
  jpa:
    database-platform: org.hibernate.dialect.Oracle12cDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
